In [ ]:
#mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import pandas as pd
import numpy as np
import xarray as xr

In [ ]:
data_centroid = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/TA/SIDANG/DATA/stasiun93.csv')
data_centroid

    Longitude  Latitude     Tanggal
0   100.37222  -0.99639   7/24/2012
1   100.37222  -0.99639   5/14/2015
2   100.29786  -0.54549   7/24/2012
3   100.29786  -0.54549  12/10/2018
4   100.29786  -0.54549    1/9/2021
..        ...       ...         ...
88   98.56000   3.50100  11/18/2020
89   98.56000   3.50100   5/29/2016
90  100.37970  -0.46630   11/9/2020
91  100.37970  -0.46630   1/28/2011
92  100.37970  -0.46630   7/22/2020

[93 rows x 3 columns]

In [ ]:
# # Pisahkan Longitude dan Latitude
# split = centroid_data["geometry"].str.split(" ", n = 2, expand=True)

# # Rename kolom
# data_centroid = split.rename(columns = {1: "Longitude", 2: "Latitude"})

# # Buang tanda ()
# data_centroid['Longitude'] = data_centroid['Longitude'].str.replace("(", "").astype(float)
# data_centroid['Latitude'] = data_centroid['Latitude'].str.replace(")","").astype(float)

# data_centroid['tanggal'] = pd.to_datetime(centroid_data['tanggal'])

In [ ]:
# data_centroid

In [ ]:
# Mengambil koordinat stasiun yang ada di Pulau Sumatera
# lat = np.unique(np.array(data_centroid['Latitude']).astype(np.float))
# lon = np.unique(np.array(data_centroid['Longitude']).astype(np.float))

# min_lat = lat-0.05
# min_lon = lon-0.05
# max_lat = lat+0.05
# max_lon = lon+0.05

In [ ]:
tabeltahun = []

for tahun in range(2000,2022):
  ds = xr.open_dataarray('/content/drive/MyDrive/Colab Notebooks/TA/SIDANG/DATA/CH GSMaP/{}.nc'.format(tahun))

  ikoordinat = []
  for i in range(len(data_centroid)):
    ikoordinat.append(
        ds.sel(lat=data_centroid.loc[i,'Latitude'],
              lon=data_centroid.loc[i,'Longitude'],
              method='nearest'
              ).to_pandas().rename('centroid_{}'.format(i))
    )
  ds.close()
  tabeltahun.append(pd.concat(ikoordinat, axis=1))

df_alltime_allstat = pd.concat(tabeltahun, axis=0)
df_alltime_allstat

,centroid_0,centroid_1,centroid_2,centroid_3,centroid_4,centroid_5,centroid_6,centroid_7,centroid_8,centroid_9,...,centroid_83,centroid_84,centroid_85,centroid_86,centroid_87,centroid_88,centroid_89,centroid_90,centroid_91,centroid_92
time,,,,,,,,,,,,,,,,,,,,,
2000-03-01 00:00:00,0.074291,0.074291,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000
2000-03-01 01:00:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000
2000-03-01 02:00:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000
2000-03-01 03:00:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000
2000-03-01 04:00:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-12-31 19:00:00,6.628601,6.628601,13.855138,13.855138,13.855138,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.260331,0.260331,0.0,0.0,0.0,0.0,15.988191,15.988191,15.988191
2021-12-31 20:00:00,4.286634,4.286634,15.910936,15.910936,15.910936,3.925942,3.925942,3.925942,3.925942,3.925942,...,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,15.070391,15.070391,15.070391
2021-12-31 21:00:00,2.677062,2.677062,2.083539,2.083539,2.083539,4.667764,4.667764,4.667764,4.667764,4.667764,...,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,2.022909,2.022909,2.022909
2021-12-31 22:00:00,1.730601,1.730601,1.571398,1.571398,1.571398,0.151681,0.151681,0.151681,0.151681,0.151681,...,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,1.783448,1.783448,1.783448
2021-12-31 23:00:00,0.689848,0.689848,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000

In [ ]:
# Menyimpan data
df_alltime_allstat.to_csv('/content/drive/MyDrive/Colab Notebooks/TA/SIDANG/DATA/ts_stasiun_gsmap.csv', index=True)